### ISSUE TITLE
README.md 

### ISSUE THREAD

**Issue by jackcarlisle** [liberty-x/liberty-x.github.io#15]
It might be useful if you included an overview to your project within the README.md so as it's easier to understand the objectives. It will then be easier to see if you were successful in what you set out to do. 

You could layout the project in sections of what, how and why in order to give a good overview.

Also if you aren't too sure on what to write initially, try and come back to it and edit it once you know.

**Comment by hdrdavies** [comment]
Hi Jack! 

Thanks for bringing that to our attention. I've now made a more detailed readme which has cleared up our objectives and will help us going forward. Thanks!
