### ISSUE TITLE
bios.html

### ISSUE THREAD

**Issue by des-des** [liberty-x/liberty-x.github.io#16]
Structure super clear from html.
I think code would looks nicer if lines were shorter where possible. e.g. think about putting the image tags in the `<a>` links on new lines + breaking the content text over new lines?

Also bios is confusing name. Maybe biogs would be better ..

**Comment by Jbarget** [comment]
https://github.com/liberty-x/liberty-x.github.io/pull/28/commits

will update "bio" description next

**Comment by Jbarget** [comment]
updated 'bio' to 'biog'
https://github.com/liberty-x/liberty-x.github.io/pull/30

**Comment by Jbarget** [comment]
https://github.com/liberty-x/liberty-x.github.io/pull/33

**Comment by Jbarget** [comment]
#33 final update
