### ISSUE TITLE
nice way to add anims

### ISSUE THREAD

**Issue by des-des** [liberty-x/liberty-x.github.io#19]
I do not think it needs it but it would be super easy to to animate the transition on the hover over the photos. If you insert the line `transition: opacity .1s;` into the styling for `.boius` [(here)](https://github.com/liberty-x/liberty-x.github.io/blob/master/css/bios.css#L25) then whenever the opacity of the elem is changed the browser would animate the transition over 0.1 seconds.

**Comment by Jbarget** [comment]
Cheers for the idea, created a pull request for it and waiting for it to be reviewed.

https://github.com/liberty-x/liberty-x.github.io/pull/40
