### ISSUE TITLE
Consider using smaller image files

### ISSUE THREAD

**Issue by katpas** [liberty-x/liberty-x.github.io#20]
![screenshot 2015-09-18 at 11 23 16](https://cloud.githubusercontent.com/assets/9627463/9957412/bab7934a-5df7-11e5-8b17-77944c9501ec.png)

Otherwise this happens on less optimal computers

**Comment by Jbarget** [comment]
thanks for the heads up! we've just learnt about mobile first design so in future it should be all good!
https://github.com/FAC6/book/blob/master/patterns/week2/mobilefirst.md
