### ISSUE TITLE
border-radius on biography pictures in bios.css

### ISSUE THREAD

**Issue by mk4111** [liberty-x/liberty-x.github.io#22]
"border-radius: 100%" applied to both the image class the div class.
Is it possible to find a slightly more 'D-R-Y' way of doing this?
(As we just discussed,) the div class border-radius effect isn't visible, so would you consider just keeping the div class square and to stick to just applying the border-radius to the image class? 
Would love to hear any other options! Really liking your website though :)

**Comment by RachBLondon** [comment]
great idea, will have a look.
