### ISSUE TITLE
Styling looks very weird, particularly in 

### ISSUE THREAD

**Issue by mantagen** [liberty-x/liberty-x.github.io#27]
IE8

![lib-x-ie8](https://cloud.githubusercontent.com/assets/12934669/9957712/59a251aa-5dfa-11e5-9524-85f299af1400.png)

**Comment by hdrdavies** [comment]
Hi Matt! Here's a link to download google chrome:

https://support.google.com/chrome/answer/95346?hl=en-GB

Thanks... philistine
